### PR TITLE
[WIP] Big Docs Update™

### LINKED ISSUE #473: Big Docs Update™
I've thrown this around for a while, but haven't really gotten around to it, so putting this up here for future reference.

As we may already know, the Sphinx-based docs hasn't been building properly since forever due to the codedoc generation failing. As proposed on #468, I'm going to outline a possible plan for a docs revamp.

* Ditch Sphinx, and figure out a new documentation system to use. ([Docusaurus](https://docusaurus.io/) perhaps?)
* The above means that the documentation files (`*.rst`) might have to be converted to Markdown.
* Convert any old codedoc-based documentation blocks into valid [JSDoc](http://usejsdoc.org/).
* Update any possibly-outdated bits in the documentation.

I will start looking into this once I finished with Webpack 4.

### PR DESCRIPTION
**Pull request by resir014**
Closes #473.

### TODO

* [x] Ditched Sphinx and replaced with Docusaurus
* [x] Convert docs pages from `.rst` to `.md` (Some Sphinx-related components are converted to raw HTML).
* [x] ~~Convert any old codedoc-based documentation blocks into valid JSDoc.~~
* [ ] Update any possibly-outdated bits in the documentation.
* [x] Add custom styles for Docusaurus site

### CODE REVIEW

**Comment by resir014** [comment]
@dtinth It seems like overriding the Docusaurus CSS is quite simple to do. Will look more into it tomorrow, it's way past midnight here.

**Comment by dtinth** [comment]
By the way, should we make `package.json` a Yarn workspace?

This allows the deps for both the main project and website to be installed in one go. Additionally, it will pave the way for us to centralize the build and publishing system for Bemuse-related packages (for example, the `bms`, `bmson`, `bemuse-notechart`, `bemuse-indexer` and `bemuse-tools` packages can be centralized into this monorepo and benefit from the main project’s build system. Furthermore, general-purpose packages such as `impure-react`, `omni-input`, `sampling-master` and `scintillator` can be turned into npm packages without the overhead of separating projects.)

**Comment by resir014** [comment]
@dtinth Yeah, sure!

**Comment by resir014** [comment]
Also, another thing that I forgot to add with the Docusaurus conversion is that MathJax parsing no longer works. Will have to convert them to images or inlined in `code` blocks

**Comment by dtinth** [comment]
That’s fine, we can add MathJax script (or KaTeX) to the page as well.

**Comment by resir014** [comment]
@dtinth Alright, I've added the MathJax scripts on the Docusaurus config. It now works normally again.

**Comment by resir014** [comment]
Current progress:

image

image

We still need to change the placeholder images (e.g. header, footer logo) when I've finished doing my thing with the styles

**Comment by resir014** [comment]
@dtinth Ready for initial design feedback. After that, I'll do some quick cleanup, then it's up to you to fill up/update the contents and replace the placeholder images.

**Comment by dtinth** [comment]
I have set up Yarn workspace and set up the build process to also generate the documentation site.

For this PR, the result can be previewed at: https://deploy-preview-479--bemuse.netlify.com/project/

When deployed to production, the URL will be https://bemuse.ninja/project/

The pathname `/project/` is up to discussion, but I think it makes more sense than `https://bemuse.ninja/bemuse/`. Since `bemusic.github.io` has been aliased to `bemuse.ninja`, they are the same domain and `bemusic.github.io` cannot be used separately...

---

The design looks great! While I preview, I think the logo is the wrong variant? (There is a variant for use on Dark background and Light background.)

Also, I prefer the navbar color to be a bit more saturated, e.g. `rgb(227, 78, 122)`.

Thanks!

**Comment by dtinth** [comment]
I added a list of colors here:

https://deploy-preview-479--bemuse.netlify.com/project/docs/developers-colors.html

**Comment by resir014** [comment]
@dtinth Awesome, thanks! Will readjust the color schemes in the docs.

**Comment by resir014** [comment]
Also, yeah. I copied the logo over from the old docs. I might be able to use the one over here: https://github.com/bemusic/bemuse/blob/master/src/app/ui/images/logo-with-shadow.svg

File: website/pages/en/index.js [hunk 1]
```diff
@@ -0,0 +1,216 @@
...
+class Index extends React.Component {
+  render () {
+    let language = this.props.language || ''
+
+    return (
+      <div>
+        <HomeSplash language={language} />
+        <div className='mainContainer'>
+          <Features />
+          <FeatureCallout />
```
Comment (dtinth) [inline website/pages/en/index.js]: In my opinion, the `Features` and `FeaturesCallout` can be omitted. We can instead use image blocks like below.

File: website/pages/en/index.js [hunk 2]
```diff
@@ -0,0 +1,216 @@
...
+          <BMSMode />
+          <KeyboardMode />
+          <LearnHow />
```
Comment (dtinth) [inline website/pages/en/index.js]: I think there is a loss of cohesion here.

If I wanted to add a new row, I needed to create a new component (above) and add it here. So, 2 places to edit. I suggest doing one of these:

- **Option A:** Inline the blocks here.

- **Option B:** Instead of 3 components, use one component (e.g. `FeatureTour`) that renders 3 blocks all at once. (We can make use of `<>` (React.Fragment) component.)

In either case, after the change, we now only need to change 1 place to add a new block.

File: website/pages/en/users.js [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+              Add your company
+            </a>
+          </div>
+        </Container>
+      </div>
+    )
+  }
+}
+
+module.exports = Users
```
Comment (dtinth) [inline website/pages/en/users.js]: In my opinion, this page can be removed.

**Comment by resir014** [comment]
@dtinth Do you think we should get rid of the `users-` and `developers-` prefix on docs pages? I initially put it there for me to easily transition the content to Markdown.

**Comment by dtinth** [comment]
@resir014 I agree to both points. Without the prefix, the URLs look more natural, and the development guide can be merged.

Another place where we can potentially merge the content is the page on how to host a music server on the wiki, which is more detailed than the one currently in the docs: https://github.com/bemusic/bemuse/wiki/How-to-Host-a-Music-Server-(Draft)

**Comment by resir014** [comment]
@dtinth Yeah, we can definitely merge some content from the wiki to the new docs site! After the merging, we can simply disable the wiki.

**Comment by resir014** [comment]
Alright, I've attempted merging contents for the music server guide from the wiki to the docs page.

Anyways, once this is finished, I might create a PR on the Docusaurus repo to have this project included on their [showcase](https://docusaurus.io/en/users.html). :D

**Comment by dtinth** [comment]
I think this is ready to merge. Thanks for your help pushing the new documentation website! ^_^
